
#include "ble_stack.h"
#include "bleplat.h"
#include "utilities_common.h"

PLACE_IN_SECTION("STATIC_STACK_APP_CALL_TABLE") void * const app_call_table[] =
{
  (void *) BLE_STACK_Event,
  (void *) BLE_STACK_ProcessRequest,
  (void *) BLEPLAT_MemCpy,
  (void *) BLEPLAT_MemSet,
  (void *) BLEPLAT_MemCmp,
  (void *) BLEPLAT_GetPartInfo,
  (void *) BLEPLAT_NvmAdd,
  (void *) BLEPLAT_NvmGet,
  (void *) BLEPLAT_NvmCompare,
  (void *) BLEPLAT_NvmDiscard,
  (void *) BLEPLAT_PkaStartP256Key,
  (void *) BLEPLAT_PkaStartDHkey,
  (void *) BLEPLAT_AesEcbEncrypt,
  (void *) BLEPLAT_AesCMACEncryptInit,
  (void *) BLEPLAT_AesCMACEncryptAppend,
  (void *) BLEPLAT_AesCMACEncryptFinish,
  (void *) BLEPLAT_RngGetRandom16,
  (void *) BLEPLAT_RngGetRandom32,
  (void *) BLEPLAT_DBmToPALevel,
  (void *) BLEPLAT_DBmToPALevelGe,
  (void *) BLEPLAT_PALevelToDBm,
  (void *) BLEPLAT_ReadTransmitPower,
  (void *) BLEPLAT_SetHighPower,
  (void *) BLEPLAT_CalculateRSSI,
  (void *) BLEPLAT_UpdateAvgRSSI,
  (void *) BLEPLAT_GetDemodCI,
  (void *) BLEPLAT_GetMaxPALevel,
  (void *) BLEPLAT_GetDefaultPALevel,
  (void *) BLEPLAT_InitCTE,
  (void *) BLEPLAT_DeinitCTE,
  (void *) BLEPLAT_CalibrateCTE,
  (void *) BLEPLAT_AntIdxRemap,
  (void *) BLEPLAT_GetCurrentSysTime,
  (void *) BLEPLAT_GetFutureSysTime64,
  (void *) BLEPLAT_StartTimer,
  (void *) BLEPLAT_StopTimer,
  (void *) BLEPLAT_SetRadioTimerValue,
  (void *) BLEPLAT_ClearRadioTimerValue,
  (void *) BLEPLAT_GetAnchorPoint,
  (void *) BLEPLAT_SetRadioCloseTimeout,
  (void *) BLEPLAT_SetRadioTimerRelativeUsValue,
};
